### ISSUE TITLE
Improve HOPR docs hosted on 

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-docs#3]
## Description
HOPR's development documentation has been recently moved to Docusaurus. 
We look for help to improve this setup.

## Tasks
Here are two issues to be tackled:
- [ ] #1 
- [ ] #2 

## Related discussion
- https://github.com/hoprnet/hopr-devrel/issues/105
- https://github.com/hoprnet/hoprnet/issues/1960

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1.0 HOPR (0.3 USD @ $0.3/HOPR)  attached to it as part of the hoprnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,326,542.11 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years from now.
Please review their action plans below:


**1) [khafidprayoga](https://gitcoin.co/khafidprayoga) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?mutate_worker_action=approve&worker=khafidprayoga) | [reject worker](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?mutate_worker_action=reject&worker=khafidprayoga))_.**

interesting! I will work on some of the problems you gave to start working on your documents hosted on Docusaurus.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154).

**Comment by gitcoinbot** [comment]
@kedziapawel Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=100)

**Comment by gitcoinbot** [comment]
@kedziapawel Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=100)

**Comment by gitcoinbot** [comment]
@kedziapawel Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=100)

**Comment by gitcoinbot** [comment]
@kedziapawel Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=1) | [3 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=3) | [5 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=5) | [10 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=10) | [100 days](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154?snooze=100)
